language: android
jdk:
  - oraclejdk8
  - oraclejdk7

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - extra-android-m2repository
    - android-23

before_install:
  - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
  - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
  - export JAVA_HOME=$JAVA7_HOME
script: ./gradlew build